### ISSUE TITLE
InvocationTargetException in version 2.1.9

### ISSUE THREAD

**Issue by perracolabs** [Giphy/giphy-android-sdk#166]
I had next exception with version 2.1.9, which I've been using just over a week now. Before it I was using 2.1.6 which showed no problems.

Unfortunately I haven't been able to reproduce it again. It happened all of the sudden when opening the Giphy's dialog.

The stack trace shows some problem with a coroutine. I cannot add more info other than this as I am not able to reproduce it:

```
Thread: main

java.lang.reflect.InvocationTargetException

StackTrace

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:666)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	... 1 more
Caused by: java.lang.InterruptedException
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:83)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at com.giphy.sdk.ui.Giphy.configure(Giphy.kt:55)
	at com.giphy.sdk.ui.Giphy.configure$default(Giphy.kt:50)
	at com.giphy.sdk.ui.views.GiphyDialogFragment.onCreate(GiphyDialogFragment.kt:184)
	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8060)
	... 3 more

```

**Update:**
I can confirm it also happens with 2.1.10, Crashed again, but I cannot see any pattern. Is when opening the dialog.

**Update 2:**
Also happens down to version 2.1.7.

**Update 3:**
The only pattern I've found is that  «if» it crashes, then such crash will only happen the very first time the dialog is  requested to open.
If the dialog successfully opened at least once then it never crashes, logically unless the app process is fully killed and restarted again.

**Comment by ALexanderLonsky** [comment]
hey @perracolabs, thank you, I'll take a look.

**Comment by ALexanderLonsky** [comment]
@perracolabs 
From the trace, I guess you don't use `Giphy.configure` but `GiphyDialogFragment.newInstance(apiKey = YOUR_API_KEY)`

To my regret, I can't reproduce it on my end, I tried many cases.
The only main difference between 2.1.6 and 2.1.7 is that `@JvmOverloads` was added to support default parameter values in Java projects.

Could you please try this version(without `@JvmOverloads`):
`implementation "com.giphy.sdk:ui:2.1.11-crash-hopeful-fix"`

It's a staging version, it requires:
```
allprojects {
    repositories {
        maven("https://oss.sonatype.org/content/repositories/staging")
    }
}
```

**Comment by perracolabs** [comment]
Unfortunately the crash happens randomly, but only when is the very first time the app process starts.
If its of any use, next is how I open Giphy. Sorry, still Java for this bit:

```
 
 public GiphyDialogFragment getDialog(@NonNull final GPHContentType activeType, boolean useDarkTheme,
                                      @NonNull final GiphyDialogFragment.GifSelectionListener listener) {
    final GPHTheme theme = (useDarkTheme == true)
            ? GPHTheme.Dark
            : GPHTheme.Light;

    final GPHSettings settings = new GPHSettings();
    settings.setTheme(theme);
    settings.setRating(RatingType.pg13);
    settings.setRenditionType(RenditionType.fixedWidth);
    settings.setGridType(GridType.waterfall);
    settings.setShowCheckeredBackground(true);
    settings.setSuggestionsBarFixedPosition(true);

    final GPHContentType[] contentTypes = new GPHContentType[5];
    contentTypes[0] = GPHContentType.sticker;
    contentTypes[1] = GPHContentType.gif;
    contentTypes[2] = GPHContentType.text;
    contentTypes[3] = GPHContentType.emoji;
    contentTypes[4] = GPHContentType.recents;
    settings.setSelectedContentType(activeType);
    settings.setMediaTypeConfig(contentTypes);

    final GiphyDialogFragment dialog = GiphyDialogFragment.Companion.newInstance(settings, Configurator.KEY_API, false);
    dialog.setGifSelectionListener(listener);
    return dialog;
}

final GiphyDialogFragment dialog = getDialog(activeType, useDarkTheme, this);
final FragmentManager fragmentManager = activity.getSupportFragmentManager();
dialog.show(fragmentManager, "giphy");


```

**Comment by ALexanderLonsky** [comment]
I see, thanks, I'll try it out using the Java demo.
Could you please try the new staging version?

**Comment by perracolabs** [comment]
That's odd but I can't seem to include the maven link, don't know if with Android Srctic Fox something changed, or I am missing something. I've included it as next:

```
allprojects {
    repositories {
        google()
        mavenCentral()
        maven("https://oss.sonatype.org/content/repositories/staging")
    }
}

```

**Comment by ALexanderLonsky** [comment]
hey @perracolabs ,

Please ignore that staging version, I don't think the problem is in JvmOverloads.

I still can't reproduce the issue, tried many ways including async calls in a loop and etc.
Also tried many times:
> So the only way to try to reproduce it, is open the app, request the dialog to open, if it opens and doesn't' crash, then kill the app process completely and repeat the test.

Could you please check if the Giphy example app(`DemoActivity`/`DemoActivityJava`) crashes for you?

**Comment by perracolabs** [comment]
OK, I'll try the demo, though is a bit tedious to test because it happens so randomly.
It can be hours working perfectly, and then suddenly crashes. So it may take a bit to give you a feedback.

The only hint I can't think of, is that the crash happens starting at version 2.1.7, therefore would be to check for code differences between versions 2.1.6 and 2.1.7.

**Comment by ALexanderLonsky** [comment]
> I'll try the demo
Thank you!

> therefore would be to check for code differences between versions 2.1.6 and 2.1.7.
I did, there were only changes to the `VideoPlayer`/`GPHVideoPlayer` and accessibility improvements like

`gifView.contentDescription = "Media # ${adapterPosition + 1} of ${adapterHelper.itemCount} "`

Nothing other than that.

**Comment by perracolabs** [comment]
An important bit I forgot to mention in the usage snipped I posted above. 

The initial one-time Giphy's configuration is done  in a background thread.
To clarify, the next call is done in a background thread:

'''
Giphy.INSTANCE.configure(appContext,  Configurator.KEY_API, false);
''' 

The initialization is synchronized, so only after configured completes Giphy's dialog code can be called, logically in the main thread.

The configuration task-thread is executed via a serial Executor Service, which runs sequentially only one task-thread at a time, but which may cancel the running task under certain circumstances.

I will verify if my code could be cancelling Giphy's configuraiton task under some circumstances. But if such is the case, as the configuration is running in a background thread then this could maybe explain the **InterruptedException** in the crash stacktrace, because at an upper lever above "Giphy.INSTANCE.configure" an Executor has cancelled the thread.

**Comment by ALexanderLonsky** [comment]
I see, yes, this might be the issue. 
Actually, you don't need to call `Giphy.INSTANCE.configure` if you provide your API key to the dialog directly, because the dialog calls `Giphy.INSTANCE.configure` itself if an API key is populated.
Though, if you use `GPHMediaView` somewhere before the configuration call then Fresco won't be initialized and it might lead to a crash because `GPHMediaView` uses it under the hood.

**Comment by perracolabs** [comment]
The reason to call **Giphy.INSTANCE.configure** in a separate thread is for the next use-case:

I noticed that there is a delay-lag on the first Giphy's instantiation time due to the instance configuration call. 
This would depend on device specs, more noticeable with older devices.

Now, when opening one of the editors in the app, the user may or "may not" use Giphy's dialog. 

So, in order to mitigate the dialog opening delay-lag, the **Giphy.INSTANCE.configure** call is done in a background thread as a preparation for "just in case" decides to use Giphy, so the dialog will open faster when (if) opened. But the background thread is executed just when opening one of the editors and not before.

The reason **Giphy.INSTANCE.configure** is not called long before, for example at the app startup, is because this is only used in the editors, as the app has multiple sections besides editors, and the idea is to reduce the amount of loaded/unused resources until really needed.

**Comment by ALexanderLonsky** [comment]
Got it.
I reproduced another crash when simultaneously calling 
`Giphy.INSTANCE.configure` in a background thread and 
`GiphyDialogFragment.Companion.newInstance` in the main thread:

**java.lang.IllegalStateException: Another SimpleCache instance uses the folder**

Fixed that by making `Giphy.INSTANCE.configure` synchronized.

I think this should fix your issue too.

Here is a staging version:

`implementation "com.giphy.sdk:ui:config-crash-hopeful-fix"`

```
allprojects {
    repositories {
        mavenCentral()
        google()
        maven("https://oss.sonatype.org/content/repositories/staging")
    }
}
```

I'll do a new official release if you confirm the staging one does not crash for you.

**Comment by perracolabs** [comment]
I can't get why Android Studio doesn't let me use this maven repository:

```
> Could not find method maven() for arguments [https://oss.sonatype.org/content/repositories/staging] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.
```

**Comment by ALexanderLonsky** [comment]
do you use groovy? then it should be
```
allprojects {
  repositories {
    google()
    mavenCentral()
    maven {
      url "https://oss.sonatype.org/content/repositories/staging"
    }
  }
}
```

**Comment by perracolabs** [comment]
All good now, will test it for a few hours.

If you have synchronized **Giphy.INSTANCE.configure** then I think it would probably be solved.

**Comment by ALexanderLonsky** [comment]
this is fixed in [v2.1.11](https://github.com/Giphy/giphy-android-sdk/releases/tag/v2.1.11)

**Comment by perracolabs** [comment]
Didn't have a problem at all since 2.1.11 was released, and head very heady testing since its released.
But, suddenly today I got this crash again, so it seams the issue still persists:

```
2021-11-25 21:12:02.586 5244-5244/<redacted> E/AndroidRuntime: FATAL EXCEPTION: main
    Process: <redacted>, PID: 5244
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:666)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
     Caused by: java.lang.InterruptedException
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:83)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
        at com.giphy.sdk.ui.Giphy.configure(Giphy.kt:56)
        at com.giphy.sdk.ui.Giphy.configure$default(Giphy.kt:51)
        at com.giphy.sdk.ui.views.GiphyDialogFragment.onCreate(GiphyDialogFragment.kt:184)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:8059)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) 
```

**Comment by ALexanderLonsky** [comment]
hey @perracolabs,
I'm sorry to hear this. 
It might be related to your delay-lag mitigation logic. 
Anyway, it points to the **runBlocking** issue. Since **Giphy.INSTANCE.configure** is already synchronized as of 2.1.11, I decided to remove **runBlocking** from it, it must work as expected without it.

Please, try this version:
`implementation "com.giphy.sdk:ui:2.1.12-config-crash-hopeful-fix"`

It's staging, so don't forget to add this:

```
allprojects {
  repositories {
    google()
    mavenCentral()
    maven {
      url "https://oss.sonatype.org/content/repositories/staging"
    }
  }
}
```

**Comment by perracolabs** [comment]
I've been testing it since last Friday and no issues with the new fix version.

**Comment by ALexanderLonsky** [comment]
thanks for the update!

**Comment by perracolabs** [comment]
Hi. What is the timeline for this fix to get released?
Thanks

**Comment by ALexanderLonsky** [comment]
Hi, 
tomorrow.

**Comment by ALexanderLonsky** [comment]
Hi @perracolabs,
[v2.1.12](https://github.com/Giphy/giphy-android-sdk/releases/tag/v2.1.12) released.
